Adjust some code after auditing strictNullChecks.
japie1235813/tensorboard pull request #29
Opened 2022-10-03 19:57 UTC by bmd3k

I made some adjustments to japie1235813/strictNull after auditing a subset of the code. I audited maybe a quarter. The following plugins remain unaudited but I have entered b/250653393 as a cleanup task to take a look at them:
* graphs
* projector
* mesh
* custom scalars

2022-10-04 05:34 UTC, gunan requested changes
Just one issue, which is internally causing build failures because the compiler behaves weirdly (IMHO, not many people agree with me) when we use `!==` compared to `!=` operator.
If the external compiler version is not OK with the `!=` operator, we can also use something like:
```
if (this._makeChartAsyncCallbackId) {
  ...
```

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
> +    if (this._raf !== null) {
For comparison to `null` please use `!=` operator. Otherwise compiler will still complain that `this._raf` may be null. Style guide does allow an exception for comparison with a null:
https://google.github.io/styleguide/tsguide.html#equality-checks

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
> +    if (this._raf !== null) {
ditto above about `!=` operator

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_line_chart2/line-chart.ts
> +  private symbolFunction: SymbolFn | undefined;
Just double checking, when I added undefined to the type here, it had a domino effect of failures. Were you able to build with strictNullChecks with this?

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_line_chart2/line-chart.ts
> +  private _defaultXRange: number[] | undefined;
ditto (verified via local build?)

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_line_chart2/line-chart.ts
> +  private _defaultYRange: number[] | undefined;
ditto (verified via local build?)

2022-10-04 05:34 UTC, gunan commented on tensorboard/components/vz_line_chart2/vz-line-chart2.ts
> +    if (this._makeChartAsyncCallbackId !== null) {
ditto above, `!=` operator

2022-10-04 05:34 UTC, gunan commented on tensorboard/plugins/distribution/vz_distribution_chart/vz-distribution-chart.ts
> +    if (this._makeChartAsyncCallbackId !== null) {
ditto above `!=` operator

2022-10-06 15:48 UTC, gunan approved these changes

2022-10-06 17:40 UTC, bmd3k commented
Just to record discussion elsewhere: All the changes seem to pass google's internal CI and I've been able to build and run my own local tensorboards.

2022-10-06 21:58 UTC, merged